ALTER TABLE chore_templates
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS period_interval INTEGER NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS period_config TEXT[] NOT NULL DEFAULT '{}',
ADD COLUMN IF NOT EXISTS track_date_only BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS rollover BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS assignment_type TEXT NOT NULL DEFAULT 'round-robin',
ADD COLUMN IF NOT EXISTS category TEXT;
